name = "capnproto-lean"
defaultTargets = ["CapnProtoLean"]
testDriver = "CapnProtoLeanTest"

[[require]]
name = "Qq"
git = "https://github.com/leanprover-community/quote4"
rev = "nightly-testing"

[[require]]
name = "numbers"
git = "https://github.com/JamesGallicchio/Numbers"
rev = "migrate-batteries-1"

[[lean_lib]]
name = "CapnProtoLean"

[[lean_lib]]
name = "CapnProtoLeanTest"
globs = ["CapnProtoLeanTest.+"]
